[package]
name = "moc_data_provider"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version="1.0.106", features = ["derive"]}
serde_with = "3.16.1"
serde_json = "1.0.51"
rsocket_rust = "0.7"
rsocket_rust_transport_tcp = "0.7.4"
rand = "0.9.2"
rust_decimal = "1"
ordered-float = {version="4", features = ["serde"]}

